// Code generated by mockery v2.47.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/es-debug/backend-academy-2024-go-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// GeneratorInitializer is an autogenerated mock type for the GeneratorInitializer type
type GeneratorInitializer struct {
	mock.Mock
}

type GeneratorInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *GeneratorInitializer) EXPECT() *GeneratorInitializer_Expecter {
	return &GeneratorInitializer_Expecter{mock: &_m.Mock}
}

// InitializeAffineTransformations provides a mock function with given fields:
func (_m *GeneratorInitializer) InitializeAffineTransformations() ([]domain.AffineTransformation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeAffineTransformations")
	}

	var r0 []domain.AffineTransformation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.AffineTransformation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.AffineTransformation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AffineTransformation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeneratorInitializer_InitializeAffineTransformations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeAffineTransformations'
type GeneratorInitializer_InitializeAffineTransformations_Call struct {
	*mock.Call
}

// InitializeAffineTransformations is a helper method to define mock.On call
func (_e *GeneratorInitializer_Expecter) InitializeAffineTransformations() *GeneratorInitializer_InitializeAffineTransformations_Call {
	return &GeneratorInitializer_InitializeAffineTransformations_Call{Call: _e.mock.On("InitializeAffineTransformations")}
}

func (_c *GeneratorInitializer_InitializeAffineTransformations_Call) Run(run func()) *GeneratorInitializer_InitializeAffineTransformations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GeneratorInitializer_InitializeAffineTransformations_Call) Return(affineTransformations []domain.AffineTransformation, err error) *GeneratorInitializer_InitializeAffineTransformations_Call {
	_c.Call.Return(affineTransformations, err)
	return _c
}

func (_c *GeneratorInitializer_InitializeAffineTransformations_Call) RunAndReturn(run func() ([]domain.AffineTransformation, error)) *GeneratorInitializer_InitializeAffineTransformations_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeFractalImage provides a mock function with given fields:
func (_m *GeneratorInitializer) InitializeFractalImage() (*domain.FractalImage, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeFractalImage")
	}

	var r0 *domain.FractalImage
	var r1 error
	if rf, ok := ret.Get(0).(func() (*domain.FractalImage, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *domain.FractalImage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.FractalImage)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeneratorInitializer_InitializeFractalImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeFractalImage'
type GeneratorInitializer_InitializeFractalImage_Call struct {
	*mock.Call
}

// InitializeFractalImage is a helper method to define mock.On call
func (_e *GeneratorInitializer_Expecter) InitializeFractalImage() *GeneratorInitializer_InitializeFractalImage_Call {
	return &GeneratorInitializer_InitializeFractalImage_Call{Call: _e.mock.On("InitializeFractalImage")}
}

func (_c *GeneratorInitializer_InitializeFractalImage_Call) Run(run func()) *GeneratorInitializer_InitializeFractalImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GeneratorInitializer_InitializeFractalImage_Call) Return(_a0 *domain.FractalImage, _a1 error) *GeneratorInitializer_InitializeFractalImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GeneratorInitializer_InitializeFractalImage_Call) RunAndReturn(run func() (*domain.FractalImage, error)) *GeneratorInitializer_InitializeFractalImage_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeNonlinearTransformations provides a mock function with given fields:
func (_m *GeneratorInitializer) InitializeNonlinearTransformations() ([]domain.Transformation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeNonlinearTransformations")
	}

	var r0 []domain.Transformation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Transformation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Transformation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transformation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GeneratorInitializer_InitializeNonlinearTransformations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeNonlinearTransformations'
type GeneratorInitializer_InitializeNonlinearTransformations_Call struct {
	*mock.Call
}

// InitializeNonlinearTransformations is a helper method to define mock.On call
func (_e *GeneratorInitializer_Expecter) InitializeNonlinearTransformations() *GeneratorInitializer_InitializeNonlinearTransformations_Call {
	return &GeneratorInitializer_InitializeNonlinearTransformations_Call{Call: _e.mock.On("InitializeNonlinearTransformations")}
}

func (_c *GeneratorInitializer_InitializeNonlinearTransformations_Call) Run(run func()) *GeneratorInitializer_InitializeNonlinearTransformations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GeneratorInitializer_InitializeNonlinearTransformations_Call) Return(nonlinearTransformations []domain.Transformation, err error) *GeneratorInitializer_InitializeNonlinearTransformations_Call {
	_c.Call.Return(nonlinearTransformations, err)
	return _c
}

func (_c *GeneratorInitializer_InitializeNonlinearTransformations_Call) RunAndReturn(run func() ([]domain.Transformation, error)) *GeneratorInitializer_InitializeNonlinearTransformations_Call {
	_c.Call.Return(run)
	return _c
}

// NewGeneratorInitializer creates a new instance of GeneratorInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGeneratorInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GeneratorInitializer {
	mock := &GeneratorInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
